server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://quiz-reward-database.cbi8c0c4kdx2.ap-northeast-2.rds.amazonaws.com:3306/<DB-NAME>?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 19941004
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG # ?? ?? ?? ?? ??
